__author__ = 'flg8r77'

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms

ZeSum = 2
ZeFib = [1,2]
keep_going = 1

while keep_going:
   NextFib = ZeFib[len(ZeFib) - 1] + ZeFib[len(ZeFib) - 2]
   if NextFib >= 4000000:
       keep_going = 0
   else:
       ZeFib.append(NextFib)
       if NextFib % 2 == 0:
           ZeSum += NextFib

print(ZeFib)
print(ZeSum)